SET DEFINE OFF

--ZNIZKA

INSERT INTO ZNIZKA (RODZAJ_ZNIZKI, PROCENT_UMAZANY) 
VALUES ('rodzinna', 37);

INSERT INTO ZNIZKA (RODZAJ_ZNIZKI, PROCENT_UMAZANY) 
VALUES ('student', 50);

INSERT INTO ZNIZKA (RODZAJ_ZNIZKI, PROCENT_UMAZANY) 
VALUES ('krwiodawca', 75);

--KLIENT

CREATE SEQUENCE seq;

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Kamil', 'Madaj', to_date('01/12/2000', 'MM/DD/RRRR'), 'student', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Emilia', 'Książkiewicz', to_date('06/02/1990', 'MM/DD/RRRR'), 'rodzinna', 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Mateusz', 'Dybek', to_date('06/12/1993', 'MM/DD/RRRR'), NULL, 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Zofia', 'Komosa', to_date('12/05/2001', 'MM/DD/RRRR'), 'student', 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Krystyna', 'Czarniak', to_date('05/12/1992', 'MM/DD/RRRR'), NULL, 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Janusz', 'Grzelczak', to_date('03/08/2002', 'MM/DD/RRRR'), 'student', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Albert', 'Świątkowski', to_date('06/04/1995', 'MM/DD/RRRR'), 'krwiodawca', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Krzysztof', 'Cieluch', to_date('09/10/1991', 'MM/DD/RRRR'), 'rodzinna', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Małgorzata', 'Handzlik', to_date('11/08/2001', 'MM/DD/RRRR'), NULL, 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (seq.nextval, 'Tobiasz', 'Ciszek', to_date('03/08/1996', 'MM/DD/RRRR'), 'rodzinna', 'M');

--LOTNISKO

ALTER SEQUENCE seq RESTART;

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Londyn Heathrow', 'Anglia');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Paryż Charles de Gaulle', 'Francja');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Frankfurt International Airport', 'Niemcy');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Amsterdam Airport ', 'Holandia');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Rzym Fiumicino', 'Włochy');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Madryt', 'Hiszpania');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Monachium', 'Niemcy');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (seq.nextval, 'Barcelona Airport', 'Hiszpania');

--MODEL

ALTER SEQUENCE seq RESTART;

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'Boeing 787-8 Dreamliner');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'Boeing 747-200');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'DHC-6 Twin Otter');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'Antonov AN-225 Mrija');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'Boeing 777-300ER');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'DC-4 Balair');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'A380-800 British Airways');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'Concorde');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'Boeing 747-300');

INSERT INTO MODEL (NR_MODELU, NAZWA) 
VALUES (seq.nextval, 'C-54D Skymaster');

--PRACOWNIK

ALTER SEQUENCE seq RESTART;

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Mariusz', 'Szuszkiewicz', to_date('01/07/1985', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Piotr', 'Gała', to_date('01/25/1981', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Waldemar', 'Świerczewski', to_date('11/14/1992', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Maja', 'Kozik', to_date('11/15/1990', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Joanna', 'Krupa', to_date('07/13/1991', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Natalia', 'Kortas', to_date('03/05/1983', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Tomasz', 'Klasa', to_date('06/09/1981', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Szymon', 'Bucior', to_date('01/02/1989', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Emil', 'Mieczkowski', to_date('07/21/1982', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (seq.nextval, 'Maria', 'Wieczorek', to_date('05/22/1990', 'MM/DD/RRRR'));

--LICENCJA

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (1, 3);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (1, 1);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (1, 4);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (2, 10);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (2, 1);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (2, 8);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (3, 7);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (3, 8);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (3, 3);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (4, 2);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (4, 8);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (4, 4);

--SAMOLOT

ALTER SEQUENCE seq RESTART;

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2013, 8);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2015, 2);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2010, 7);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2005, 4);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2008, 5);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2014, 1);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2019, 7);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2010, 10);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2013, 8);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (seq.nextval, 2010, 1);

--LOT

ALTER SEQUENCE seq RESTART;

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('04/16/2019', 'MM/DD/RRRR'), 240, 3, 5, 1);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('06/23/2016', 'MM/DD/RRRR'), 270, 2, 8, 3);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('01/13/2019', 'MM/DD/RRRR'), 240, 10, 7, 2);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('05/31/2017', 'MM/DD/RRRR'), 120, 1, 6, 3);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('01/01/2015', 'MM/DD/RRRR'), 150, 8, 7, 5);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('09/26/2012', 'MM/DD/RRRR'), 240, 7, 1, 5);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('09/23/2015', 'MM/DD/RRRR'), 60, 3, 3, 4);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('03/29/2017', 'MM/DD/RRRR'), 90, 4, 6, 3);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('07/23/2010', 'MM/DD/RRRR'), 60, 2, 8, 7);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (seq.nextval, to_date('03/19/2019', 'MM/DD/RRRR'), 90, 4, 2, 3);

--ROLA_W_LOCIE

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (1, 3, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (1, 5, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (1, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (2, 4, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (2, 6, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (2, 8, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (3, 2, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (3, 8, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (3, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (4, 2, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (4, 6, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (4, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (5, 2, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (5, 7, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (5, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (6, 3, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (6, 7, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (6, 10, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (7, 3, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (7, 7, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (7, 10, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (8, 1, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (8, 6, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (8, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (9, 4, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (9, 5, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (9, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (10, 1, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (10, 8, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (10, 10, 'mechanik');

--MIEJSCE

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 10);

--BILET

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('NZY114', 1, 3, 1, 4, 141.78);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('RND132', 1, 3, 2, 2, 92.16);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('YMD153', 1, 3, 4, 3, 70.89);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('NIE210', 2, 2, 1, 10, 139.0);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('BIM239', 2, 2, 3, 9, 90.35);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('YVY257', 2, 2, 5, 7, 69.5);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('QZS315', 3, 10, 1, 5, 144.36);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('HHC332', 3, 10, 3, 2, 93.83);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('IBP359', 3, 10, 5, 9, 72.18);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('PFW415', 4, 1, 1, 5, 121.02);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('HMF431', 4, 1, 3, 1, 78.66);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('EOM457', 4, 1, 4, 7, 60.51);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('SGD512', 5, 8, 1, 2, 142.76);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('LEJ535', 5, 8, 3, 5, 92.79);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('WTX553', 5, 8, 4, 3, 71.38);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('GOQ610', 6, 7, 1, 10, 160.18);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('GGR638', 6, 7, 3, 8, 104.12);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('WBP655', 6, 7, 5, 5, 80.09);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('WEZ715', 7, 3, 1, 5, 121.54);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('FHQ738', 7, 3, 3, 8, 79.0);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('KZD756', 7, 3, 5, 6, 60.77);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('IVV812', 8, 4, 1, 2, 159.82);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('DEX838', 8, 4, 3, 8, 103.88);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('GAL850', 8, 4, 4, 10, 79.91);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('IJE910', 9, 2, 1, 10, 136.18);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('QRS931', 9, 2, 3, 1, 88.52);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('UJG957', 9, 2, 5, 7, 68.09);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('DTE018', 10, 4, 1, 8, 167.04);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('EQC031', 10, 4, 3, 1, 108.58);

INSERT INTO BILET (KOD_BILETU, NR_LOTU, NR_SAMOLOTU, NR_MIEJSCA, NR_KLIENTA, CENA) 
VALUES ('YRA053', 10, 4, 5, 3, 83.52);

DROP SEQUENCE seq;