SET DEFINE OFF

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (1, 'Kamil', 'Madaj', to_date('01/12/2000', 'MM/DD/RRRR'), 'student', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (2, 'Emilia', 'Książkiewicz', to_date('06/02/1990', 'MM/DD/RRRR'), 'rodzinna', 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (3, 'Mateusz', 'Dybek', to_date('06/12/1993', 'MM/DD/RRRR'), NULL, 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (4, 'Zofia', 'Komosa', to_date('12/05/2001', 'MM/DD/RRRR'), 'student', 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (5, 'Krystyna', 'Czarniak', to_date('05/12/1992', 'MM/DD/RRRR'), NULL, 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (6, 'Janusz', 'Grzelczak', to_date('03/08/2002', 'MM/DD/RRRR'), 'student', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (7, 'Albert', 'Świątkowski', to_date('06/04/1995', 'MM/DD/RRRR'), 'krwiodawca', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (8, 'Krzysztof', 'Cieluch', to_date('09/10/1991', 'MM/DD/RRRR'), 'rodzinna', 'M');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (9, 'Małgorzata', 'Handzlik', to_date('11/08/2001', 'MM/DD/RRRR'), NULL, 'K');

INSERT INTO KLIENT (NR_KLIENTA, IMIE, NAZWISKO, DATA_URODZENIA, RODZAJ_ZNIZKI, PLEC) 
VALUES (10, 'Tobiasz', 'Ciszek', to_date('03/08/1996', 'MM/DD/RRRR'), 'rodzinna', 'M');

