SET DEFINE OFF

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (1, to_date('04/16/2019', 'MM/DD/RRRR'), 240, 3, 5, 1);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (2, to_date('06/23/2016', 'MM/DD/RRRR'), 270, 2, 8, 3);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (3, to_date('01/13/2019', 'MM/DD/RRRR'), 240, 10, 7, 2);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (4, to_date('05/31/2017', 'MM/DD/RRRR'), 120, 1, 6, 3);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (5, to_date('01/01/2015', 'MM/DD/RRRR'), 150, 8, 7, 5);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (6, to_date('09/26/2012', 'MM/DD/RRRR'), 240, 7, 1, 5);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (7, to_date('09/23/2015', 'MM/DD/RRRR'), 60, 3, 3, 4);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (8, to_date('03/29/2017', 'MM/DD/RRRR'), 90, 4, 6, 3);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (9, to_date('07/23/2010', 'MM/DD/RRRR'), 60, 2, 8, 7);

INSERT INTO LOT (NR_LOTU, DATA_LOTU, CZAS_LOTU_MIN, NR_SAMOLOTU, LOTNISKO_STARTOWE, LOTNISKO_DOCELOWE) 
VALUES (10, to_date('03/19/2019', 'MM/DD/RRRR'), 90, 4, 2, 3);

