SET DEFINE OFF

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (1, 'Londyn Heathrow', 'Anglia');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (2, 'Paryż Charles de Gaulle', 'Francja');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (3, 'Frankfurt International Airport', 'Niemcy');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (4, 'Amsterdam Airport ', 'Holandia');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (5, 'Rzym Fiumicino', 'Włochy');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (6, 'Madryt', 'Hiszpania');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (7, 'Monachium', 'Niemcy');

INSERT INTO LOTNISKO (NR_LOTNISKA, NAZWA, KRAJ_POLOZENIA) 
VALUES (8, 'Barcelona Airport', 'Hiszpania');