SET DEFINE OFF

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 1);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 2);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 3);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 4);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 5);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 6);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 7);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 8);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 9);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (1, 'biznes', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (2, 'pierwsza', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (3, 'pierwsza', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (4, 'ekonomiczna', 10);

INSERT INTO MIEJSCE (NR_MIEJSCA, KLASA, NR_SAMOLOTU) 
VALUES (5, 'ekonomiczna', 10);

