SET DEFINE OFF

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (1, 'Boeing 787-8 Dreamliner');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (2, 'Boeing 747-200');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (3, 'DHC-6 Twin Otter');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (4, 'Antonov AN-225 Mrija');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (5, 'Boeing 777-300ER');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (6, 'DC-4 Balair');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (7, 'A380-800 British Airways');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (8, 'Concorde');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (9, 'Boeing 747-200');

INSERT INTO MODELE (NR_MODELU, NAZWA) 
VALUES (10, 'C-54D Skymaster');

