SET DEFINE OFF

INSERT INTO ZNIZKI (RODZAJ_ZNIZKI, PROCENT_UMAZANY) 
VALUES ('rodzinna', 37);

INSERT INTO ZNIZKI (RODZAJ_ZNIZKI, PROCENT_UMAZANY) 
VALUES ('student', 50);

INSERT INTO ZNIZKI (RODZAJ_ZNIZKI, PROCENT_UMAZANY) 
VALUES ('krwiodawca', 75);