version: '3'

services:
  mqtt_broker:
    container_name: mqttBroker
    build:
      context: mqttBroker
      dockerfile: Dockerfile
    ports:
      - "1883:1883"

  fastapi_service:
    container_name: fastapi
    build:
      context: fastapiService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mqtt_app:
    build:
      context: mqttApp
      dockerfile: Dockerfile
    depends_on:
      - fastapi_service
      - mqtt_broker

  mqtt_subscriber:
    build:
      context: ./mqttSubscriber
      dockerfile: Dockerfile
    depends_on:
      - mqtt_broker
