SET DEFINE OFF

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (1, 3);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (1, 1);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (1, 4);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (2, 10);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (2, 1);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (2, 8);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (3, 7);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (3, 8);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (3, 3);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (4, 2);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (4, 8);

INSERT INTO LICENCJA (NR_PRACOWNIKA, NR_MODELU) 
VALUES (4, 4);

