SET DEFINE OFF

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (1, 'Mariusz', 'Szuszkiewicz', to_date('01/07/1985', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (2, 'Piotr', 'Gała', to_date('01/25/1981', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (3, 'Waldemar', 'Świerczewski', to_date('11/14/1992', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (4, 'Maja', 'Kozik', to_date('11/15/1990', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (5, 'Joanna', 'Krupa', to_date('07/13/1991', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (6, 'Natalia', 'Kortas', to_date('03/05/1983', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (7, 'Tomasz', 'Klasa', to_date('06/09/1981', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (8, 'Szymon', 'Bucior', to_date('01/02/1989', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (9, 'Emil', 'Mieczkowski', to_date('07/21/1982', 'MM/DD/RRRR'));

INSERT INTO PRACOWNIK (NR_PRACOWNIKA, IMIE, NAZWISKO, DATA_URODZENIA) 
VALUES (10, 'Maria', 'Wieczorek', to_date('05/22/1990', 'MM/DD/RRRR'));

