SET DEFINE OFF

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (1, 3, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (1, 5, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (1, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (2, 4, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (2, 6, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (2, 8, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (3, 2, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (3, 8, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (3, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (4, 2, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (4, 6, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (4, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (5, 2, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (5, 7, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (5, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (6, 3, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (6, 7, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (6, 10, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (7, 3, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (7, 7, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (7, 10, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (8, 1, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (8, 6, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (8, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (9, 4, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (9, 5, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (9, 9, 'mechanik');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (10, 1, 'pilot');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (10, 8, 'steward');

INSERT INTO ROLA_W_LOCIE (NR_LOTU, NR_PRACOWNIKA, ROLA) 
VALUES (10, 10, 'mechanik');

