SET DEFINE OFF

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (1, 2013, 8);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (2, 2015, 2);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (3, 2010, 7);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (4, 2005, 4);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (5, 2008, 5);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (6, 2014, 1);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (7, 2019, 7);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (8, 2010, 2);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (9, 2013, 8);

INSERT INTO SAMOLOT (NR_SAMOLOTU, ROK_PRODUKCJI, NR_MODELU) 
VALUES (10, 2010, 4);

